### PR TITLE
Changed http to https, explicitly imported the GPG key, and made the template more succinct

### PR DESCRIPTION
**Pull request by pgporada**
```
---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    elrepo_repos:
      elrepo: True
      elrepo_extras: True
      elrepo_kernel: False
      elrepo_testing: True

  roles:
    - ./ansible
```

```
### Name: ELRepo.org Community Enterprise Linux Repository for el7
### URL: http://elrepo.org/

[elrepo]
name=ELRepo.org Community Enterprise Linux Repository - el7
baseurl=http://elrepo.org/linux/elrepo/el7/$basearch/
	http://mirrors.coreix.net/elrepo/elrepo/el7/$basearch/
	http://jur-linux.org/download/elrepo/elrepo/el7/$basearch/
	http://repos.lax-noc.com/elrepo/elrepo/el7/$basearch/
	http://mirror.ventraip.net.au/elrepo/elrepo/el7/$basearch/
mirrorlist=http://mirrors.elrepo.org/mirrors-elrepo.el7
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
protect=0

[elrepo-testing]
name=ELRepo.org Community Enterprise Linux Testing Repository - el7
baseurl=http://elrepo.org/linux/testing/el7/$basearch/
	http://mirrors.coreix.net/elrepo/testing/el7/$basearch/
	http://jur-linux.org/download/elrepo/testing/el7/$basearch/
	http://repos.lax-noc.com/elrepo/testing/el7/$basearch/
	http://mirror.ventraip.net.au/elrepo/testing/el7/$basearch/
mirrorlist=http://mirrors.elrepo.org/mirrors-elrepo-testing.el7
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
protect=0

[elrepo-kernel]
name=ELRepo.org Community Enterprise Linux Kernel Repository - el7
baseurl=http://elrepo.org/linux/kernel/el7/$basearch/
	http://mirrors.coreix.net/elrepo/kernel/el7/$basearch/
	http://jur-linux.org/download/elrepo/kernel/el7/$basearch/
	http://repos.lax-noc.com/elrepo/kernel/el7/$basearch/
	http://mirror.ventraip.net.au/elrepo/kernel/el7/$basearch/
mirrorlist=http://mirrors.elrepo.org/mirrors-elrepo-kernel.el7
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
protect=0

[elrepo-extras]
name=ELRepo.org Community Enterprise Linux Extras Repository - el7
baseurl=http://elrepo.org/linux/extras/el7/$basearch/
	http://mirrors.coreix.net/elrepo/extras/el7/$basearch/
	http://jur-linux.org/download/elrepo/extras/el7/$basearch/
	http://repos.lax-noc.com/elrepo/extras/el7/$basearch/
	http://mirror.ventraip.net.au/elrepo/extras/el7/$basearch/
mirrorlist=http://mirrors.elrepo.org/mirrors-elrepo-extras.el7
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
protect=0
```

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [./ansible : Assert that prerequisites exist] *****************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [./ansible : Set elrepo_ver fact (el7)] ***********************************
ok: [localhost]

TASK [./ansible : Set elrepo_ver fact (el6)] ***********************************
skipping: [localhost]

TASK [./ansible : Set elrepo_ver fact (el5)] ***********************************
skipping: [localhost]

TASK [./ansible : Acquire the ELRepo GPG key] **********************************
ok: [localhost]

TASK [./ansible : Execute mktemp] **********************************************
changed: [localhost]

TASK [./ansible : Create temporary package] ************************************
changed: [localhost]

TASK [./ansible : Install elrepo-release] **************************************
ok: [localhost] => (item=[u'/tmp/tmp.kVUqrrAFY3.rpm'])

TASK [./ansible : Configure elrepo.repo] ***************************************
changed: [localhost]

TASK [./ansible : Erase temporary package] *************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=9    changed=4    unreachable=0    failed=0  
```

### CODE REVIEW

**Comment by tkimball83** [comment]
I like these changes, however I'm not sure we want to reboot right after we install the kernel as there could be other roles/tasks to be run after the elrepo role.  Thoughts?

Second, we do not necessarily want to install gcc everywhere as it may not have been removed prior.

Lastly, the elrepo kernel packages should update grub (minus setting the new kernel to default).  Was that not the case in your environment?

**Comment by pgporada** [comment]
:O I'm really sorry. Some of these changes should have been on a branch and not on this PR.

**Comment by pgporada** [comment]
-  I'm not sure we want to reboot right after we install the kernel as there could be other roles/tasks to be run after the elrepo role. Thoughts?
Totally agree. This was my fault for not properly branching my code and pushing directly to my master branch.

- Second, we do not necessarily want to install gcc everywhere as it may not have been removed prior.
Installing the kernel-{ml,lt} and removing the old kernel removed gcc and some other packages. I've always had to add them back in.

- Lastly, the elrepo kernel packages should update grub (minus setting the new kernel to default). Was that not the case in your environment?
This was not the case for my env (centos7).

**Comment by tkimball83** [comment]
**Installing the kernel-{ml,lt} and removing the old kernel removed gcc and some other packages. I've always had to add them back in.**

I'm stating that sometimes we simply don't want a complier on a system.  Therefore we don't want to install it after the kernel upgrade if it wasn't there prior.

**This was not the case for my env (centos7).**

I just tested on a CentOS 7 virtual machine and grub2.cfg was updated:

`[root@centos7 ~]# grep 4.4.51 /etc/grub2.cfg

menuentry 'CentOS Linux (4.4.51-1.el7.elrepo.x86_64) 7 (Core)' --class centos --class gnu-linux --class gnu --class os --unrestricted $menuentry_id_option 'gnulinux-3.10.0-123.el7.x86_64-advanced-fdafe805-871b-4828-a62f-f48aee25ca48' {
	linux16 /vmlinuz-4.4.51-1.el7.elrepo.x86_64 root=/dev/mapper/centos-root ro rd.lvm.lv=centos/swap vconsole.font=latarcyrheb-sun16 rd.lvm.lv=centos/root crashkernel=auto  vconsole.keymap=us rhgb quiet LANG=en_US.UTF-8
	initrd16 /initramfs-4.4.51-1.el7.elrepo.x86_64.img`

Very odd that it didn't update your configuration upon install...

**Comment by tkimball83** [comment]
I cherry-picked most of your changes and committed them to master.  I only added grub support for <= el7 too.  Please review/test the changes at your earliest convenience.  If all is well I'll close out this pull request.

https://github.com/linuxhq/ansible-role-elrepo/commit/1ccf0e62d8253752330560d2fcbc6a7792758845

**Comment by pgporada** [comment]
I read through the changes and they look good to me.

**Pull request closed without merging**
